Config({
    "network-name": "شبكة دارك نت",
    "service-number": "735501599",
    "login-type": "both", 
    "speed-select": 0 ,
    "speed-var": "speed",
    "speed-option": "",
    "news-line": "مرحبا  بكم  في شبكتنا * تذكر أن الله ينظر إليك فلا تجعله أهون الناظرين إليك" ,
    "input-autocomplete": "on",
    "input-type": "text",
    "input-rm-white-spaces": 1,
    "input-to-lower": 0,
    "input-to-upper": 0,
    "input-to-arabic-numbers": 1,
    "input-only-numbers": 0,
    "input-no-numbers": 0,
    "input-only-alphanumeric": 0,
    "enable-hot-cookie": 1 ,
    "enable-hot-blocker": 1,
    "clear-router-cookie": 1,
    "clear-hot-cookie": 1,
    "block-time": 2,
    "try-count": 5,
    "warn-when": 3,
    "warn-message": "تحذير !! عدد محاولاتك الخاطئة اصبح {{tryCounter}} محاولات, عدد المحاولات المسموح بها هي {{tryCount}} محاولات فقط, عدد محاولاتك المتبقية {{restTryCount}} محاولات, سيتم حظرك لمدة {{blockTime}} دقائق اذا تجاوزت العدد المسموح للمحاولات",
    "price-button": true,
    "sell-point-button": true,
    "show-date-field": true,
    "loan-button": true,
    "loan-text": "توصيل شبكتنا الى منزلك - مازالت شبكتنا جديدة لذلك يصعب علينا تغطية الأماكن البعيدة لكن أبلغنا عبر الواتس أب بمكانك وسنسعى إلى توصيل شبكتنا إليك قدر المستطاع - لا تترددوا بالتواصل معنا عبر الواتس أب 735501599",
    "redirect-to-esterahah": "",
    "redirect-to-mobasher": "",
    "profiles": [{"price":"200 ريال","time":"4 ساعات","transfer":"550 ميجا","validity":"3 أيام"},{"price":"500 ريال","time":"12 ساعة","transfer":"1.5 جيجا","validity":"7 أيام"},{"price":"1000 ريال","time":"مفتوح","transfer":"3 جيجا","validity":"12 يوم"},{"price":"3000 ريال","time":"مفتوح","transfer":"10 جيجا","validity":"شهر"},{"price":"10 ألف ريال","time":"مفتوح","transfer":"40 جيجا","validity":"شهر"}] ,
    "sell-points": [{"name":"بقالة بشير اليوسفي"},{"name":"بقالة عبدالله الشرعبي - قريبا"},{"name":"جميع البقالات القريبة منك - قريبا"}]
})
